// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Offline_System;

#nullable disable

namespace Offline_System.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20240122082056_init database")]
    partial class initdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Offline_System.Models.Data.Employees", b =>
                {
                    b.Property<int>("EmployeesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeesID"));

                    b.Property<string>("EmployeesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeesID");

                    b.ToTable("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
